### PR TITLE
Add Wayland zwp_input_method_v1 support

### LINKED ISSUE #604: wayland 세션에서 qt와 gtk를 사용하지 않는 프로그램들 한글 입력 불가
wayland 세션에서 emacs, intellij 등 qt와 gtk를 사용하지 않는 프로그램들은 한글을 입력할수가 없습니다.
kime-check를 실행하면
Ok       Config file                   
Ok       Engine works                  
Ignore   XMODIFIERS has @im=kime       (Session type is wayland not x11)
Ok       GTK_IM_MODULE has kime        
Ok       QT_IM_MODULE has kime         
Ok       LANG has UTF-8    
이렇게 나옵니다.

다른 입력기에서는 wayland세션에서도  XMODIFIERS=@im=<입력기> 이렇게 설정해서 
입력이 가능합니다.

### PR DESCRIPTION
**Pull request by Jhyub**
## Summary

This PR introduces support for Wayland zwp_input_method_v1.  
This enables IME input with non-GTK/QT wayland software under certain compositors such as KWin Wayland.
The PR also introduces minor changes in desktop files to make kime functional under KDE Plasma Wayland.

## Note

* This PR closes #604 #638 
* This PR has been tested under my environment: Arch Linux, kwin 5.27.10 (kwin_wayland)

## Checklist

- [ ] I have documented my changes properly to adequate places
- [x] I have updated the docs/CHANGELOG.md

### CODE REVIEW

**Comment by black7375** [comment]
Plasma Wayland 세션에서 KIME가 동작함을 확인하였습니다.

image
image
image

**Comment by OctopusET** [comment]
It works with Weston 13.0.0

To use kime on weston, you need to add this to weston.ini
```
[input-method]
path=/usr/bin/kime
```

**Comment by Jhyub** [comment]
I did not implement `kime-check` for weston because it seems to be impossible to find out if kime is running under weston.

**Comment by OctopusET** [comment]
It's pretty messed up, but there is a way to get the compositor name without using the`XDG_CURRENT_DESKTOP` env.

https://stackoverflow.com/questions/69302630/wayland-client-get-compositor-name

**Comment by OctopusET** [comment]
And even in sway, there's no guarantee sway session always have the `XDG_CURRENT_DESKTOP` env.
https://github.com/swaywm/sway/pull/4876

**Comment by Jhyub** [comment]
It seems better not to unwrap `env::var("XDG_CURRENT_DESKTOP")` then...

**Comment by Jhyub** [comment]
> It's pretty messed up, but there is a way to get the compositor name without using the`XDG_CURRENT_DESKTOP` env.
> 
> https://stackoverflow.com/questions/69302630/wayland-client-get-compositor-name

This method seems a little bit too hacky to use... maybe it might be better to detect if weston is installed? (such as if `/usr/share/weston` exists)

**Comment by OctopusET** [comment]
IMHO, I don't think it's the IME's job to check if it works or not.
And yeah, that solution is really hacky way, I guess if you really want to add some checker for the Weston. Checking software like neofetch would be a good way to find the way to get a compositor's name.

**Comment by Jhyub** [comment]
Since that would result in adding another dependency, and considering that weston doesn't seem to have many real-world use cases (if I understood its project goals correctly) it seems more reasonable to me as well not to implement `kime-check` for it.

**Pull request merged**
