### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by BobinMathew**
## Checklist

- [ ] I have documented my changes properly to adequate places
- [ ] I have updated the docs/CHANGELOG.md

### CODE REVIEW

**Comment by BobinMathew** [comment]
issue #490

**Review by Riey — APPROVED** [review]

**Comment by Aspie96** [comment]
Note, @Riey.

I know this pull request is old.

I am writing this just because I know that you learned about the CC only trough the referenced issue, so you may not be aware of this.

Please know that the document, while very popular, is highly controversial. It has been at the center of many controversies (such as in the Linux Kernel, when some contributors thretened to revoke the license when it got imposed upon them. Luckly, revoking the GPL is likely legally impossible).

Because of American culture it is supported by many large companies and, while contributors often do not want it, maintainers adopt it, partly to avoid being villified (which has happened to those refusing to adopt it, in some instances).

The Contributor Covenant comes as a *pledge*, meaning that open source contributors are forced to accept a pledge in order to be able to contribute code, something that would be recognized as unreasonable in most other contexts.

It is not useful for projects, it is merely a political tool for the author. Indeed, the author recognizes it as a political tool: https://twitter.com/CoralineAda/status/1041465346656530432. Why does GitHub support this document? It's PR: https://twitter.com/CoralineAda/status/1194702830495510529

A code of conduct is *not* a necessary file, nor is it necessary to ask contributors to make a pledge before giving their code away for free. There is no real evidence that it is useful and there are many reasons to believe it is harmful. In addition, even the Contributor Covenant website itself advises against adopting it unless you have the resources to moderate and enforce it: https://www.contributor-covenant.org/

> As a leader you are responsible for the safe, fair, and transparent enforcement of your community’s code of conduct. A code of conduct without such enforcement sends a false signal that a community is welcoming and inclusive, which can have a disastrous impact on marginalized or otherwise vulnerable people.

In essence, if someone else misbehaves and you don't have the resources to moderate in that moment (maybe because you are the only maintainer), then you are morally responsable for the violation of the pledge.

The Contributor Covenant is not a standard (not de jure, nor de facto), it is merely an unfortunate trend.

I don't want to start a fight. You have the right to have this, it's your repo. I understand I have never contributed anything, I'm here in peace. Just evaluate whether you should reconsider this, given the additional information.

**Comment by Riey** [comment]
@Aspie96 Thank you, I'm not native English speaker so correct me if I know something wrong.

I think coc is kind of "Please don't do such things" and not legal thing.

As a maintainer, I already have permission to select which contribution to accept or not regardless of coc. It just specify some disallowed behaviors which people already implicitly followed(No one want to see hate speech in community).

I don't think existence of coc changes too much. It's true that coc not very useful in this small community because only I have permission but when it becomes bigger could be helpful to other maintainers deal with trouble.

**Comment by xnuk** [comment]
Existence of CoC makes me and other contributors feel safe, because they (or the project) decided not to do any of hate speech, even though it's just a pledge. And if I get hate speech from here, I don't have to put a big effort to explain why that is a hate speech, I would just saying "Please read and follow our CoC" because:

> We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, religion, or sexual identity
and orientation.

And that makes me feel safe.

**Comment by Aspie96** [comment]
Hi, @Riey and thanks @xnuk for their point of view.

> I think coc is kind of "Please don't do such things" and not legal thing.

(INAL)

Whether it is a legal contract is, as far as I know, an open question which may vary from jurisdiction. The question was previously asked (but never really answered) here: https://github.com/EthicalSource/contributor_covenant/issues/284

If it is, then it might possibly expose the maintainer to liability.

> As a maintainer, I already have permission to select which contribution is acceptable or not regardless of coc. It just specify some disallowed behaviors which people already implicitly followed(No one want to see hate speech in community).
> And that makes me feel safe.

The issues I mentioned aren't about the specified rules, but rather the fact that they come in the form, and with the moral weight of, a pledge. Some other codes of conduct simply specify rules, having a similar standard (they may even be clearer), such as the Ruby code of conduct, the Debian code of conduct or the OpenSSL code of conduct.

**Comment by Riey** [comment]
> The issues I mentioned aren't about the specified rules, but rather the fact that they come in the form, and with the moral weight of, a pledge.

I got your point. so you think current CoC's expression is too strong right? I don't know how strong the nuance of the word is.

> Some other codes of conduct simply specify rules, having a similar standard (they may even be clearer), such as the Ruby code of conduct, the Debian code of conduct or the OpenSSL code of conduct.

I just see those CoC it seems very nice and clear. It would be good to replace current CoC with more simple one.

However, I don't have enough time for doing now. I'll consider it later.

**Pull request merged**
