### PR TITLE
Embed d2coding font file

### LINKED ISSUE #611: kime-xim 실행 시에 panic 발생
3.0 이후 버전에서 kime-xim 실행 시 폰트가 설치되어 있지 않은 경우 panic이 발생합니다.

```
$ kime-xim
[ INFO] Found previous XIM_SERVER it will overrided
[ INFO] Start server win: 73400320
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/frontends/xim/src/handler.rs:45:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by Riey**
## Summary

Fix #611

## Checklist

- [x] I have documented my changes properly to adequate places
- [x] I have updated the docs/CHANGELOG.md

### CODE REVIEW

**Comment by OctopusET** [comment]
What about let package maintainer do this thing?

**Comment by Riey** [comment]
> What about let package maintainer do this thing?

Seems reasonable. But font should be universally available such as Noto.

**Comment by Riey** [comment]
@OctopusET I'll try it later.

**Comment by OctopusET** [comment]
Okay, great

**Pull request closed without merging**
