### PR TITLE
#160 Add Project Logo

### PR DESCRIPTION
**Pull request by So-chiru**
## Summary

kime-roundy-default
with text

kime-roundy-default-without-text
without text

## Note

I'll update the logo if there is the better design or change request.

### CODE REVIEW

**Comment by So-chiru** [comment]
Solves #160

**Comment by Riey** [comment]
It looks really cool! and I think transparent background is perfect, however I like gray color but is there colored version for comparsion?

**Comment by So-chiru** [comment]
Screen Shot 2021-02-15 at 2 20 11 PM
#89320D - Rusty Brown (BG Highlight)


Screen Shot 2021-02-15 at 2 21 16 PM
#0078ff - Accent Blue


kime-roundy-default-bluegrey
Blue favor Grey Gradient


kime-roundy-default-rust-carlo
Rust #b53c10 - Monte Carlo #89cfd4


kime-roundy-default-brown-orange
Brown Tone Orange - Orange Gradient

**Comment by Riey** [comment]
I like `Blue favor Grey Gradient` color and without `Korean Input Method Editor` version can you update pr? I'll merge that

**Comment by So-chiru** [comment]
kime-roundy-default-without-text-bluegrey

Screen Shot 2021-02-15 at 6 19 51 PM

@Riey Just pushed the commit!

**Review by Riey — APPROVED** [review]

**Pull request merged**
